// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1alpha5 "github.com/weaveworks/eksctl/pkg/apis/eksctl.io/v1alpha5"
)

// GetterInterface is an autogenerated mock type for the GetterInterface type
type GetterInterface struct {
	mock.Mock
}

type GetterInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *GetterInterface) EXPECT() *GetterInterface_Expecter {
	return &GetterInterface_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, capabilityName
func (_m *GetterInterface) Get(ctx context.Context, capabilityName string) ([]v1alpha5.Capability, error) {
	ret := _m.Called(ctx, capabilityName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []v1alpha5.Capability
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]v1alpha5.Capability, error)); ok {
		return rf(ctx, capabilityName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []v1alpha5.Capability); ok {
		r0 = rf(ctx, capabilityName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1alpha5.Capability)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, capabilityName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetterInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type GetterInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - capabilityName string
func (_e *GetterInterface_Expecter) Get(ctx interface{}, capabilityName interface{}) *GetterInterface_Get_Call {
	return &GetterInterface_Get_Call{Call: _e.mock.On("Get", ctx, capabilityName)}
}

func (_c *GetterInterface_Get_Call) Run(run func(ctx context.Context, capabilityName string)) *GetterInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GetterInterface_Get_Call) Return(_a0 []v1alpha5.Capability, _a1 error) *GetterInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetterInterface_Get_Call) RunAndReturn(run func(context.Context, string) ([]v1alpha5.Capability, error)) *GetterInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetterInterface creates a new instance of GetterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetterInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetterInterface {
	mock := &GetterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
