// +build release

package main
// This file was generated by version_generate.go; DO NOT EDIT.
var builtAt  = "" // will be set by goreleaser tool
var gitCommit = "" // will be set by goreleaser tool
var gitTag = "0.1.11"
