// +build ignore

package main

import (
	"fmt"
	"os"
	"strings"
)

func main() {
	lines := []string{
		"// +build release",
		"",
		"package main",
		"// this file was generated by version_generate.go",
		`var builtAt  = "" // will be set by goreleaser tool`,
		`var gitCommit = "" // will be set by goreleaser tool`,
		fmt.Sprintf("var gitTag = %q", os.Getenv("RELEASE_GIT_TAG")),
	}

	f, err := os.Create("version_release.go")
	if err != nil {
		os.Exit(1)
	}

	defer f.Close()

	if _, err := fmt.Fprintln(f, strings.Join(lines, "\n")); err != nil {
		os.Exit(2)
	}
}
