// +build release

package main

import (
	"bytes"
	"io/ioutil"
	"log"
	"os"

	"github.com/blang/semver"
	. "github.com/dave/jennifer/jen"
	"github.com/pkg/errors"

	"github.com/weaveworks/eksctl/pkg/version"
)

const versionFilename = "../release.go"
const defaultPreReleaseId = "dev"
const defaultReleaseCandidate = "rc.0"

func main() {
	if len(os.Args) < 2 {
		log.Fatal("missing argument. Expected 'release', 'release-candidate' or 'development'")
		return
	}

	command := os.Args[1]
	rc := ""
	if len(os.Args) > 2 {
		rc = os.Args[2]
	}

	var newVersion, newPreRelease string
	switch command {
	case "release":
		newVersion, newPreRelease = prepareRelease()
	case "release-candidate":
		newVersion, newPreRelease = prepareReleaseCandidate(rc)
	case "development":
		newVersion, newPreRelease = nextDevelopmentIteration()
	default:
		log.Fatalf("unknown option %q. Expected 'release', 'release-candidate' or 'development'", command)
		return
	}

	writeVersionToFile(newVersion, newPreRelease, versionFilename)
	return
}

func prepareRelease() (string, string) {
	return version.Version, ""
}

func prepareReleaseCandidate(rc string) (string, string) {
	if rc == "" {
		return version.Version, defaultReleaseCandidate
	}
	return version.Version, rc
}

func nextDevelopmentIteration() (string, string) {
	ver, err := semver.Make(version.Version)
	if err != nil {
		log.Fatal(errors.Wrapf(err, "could not parse version %q", version.Version))
	}
	ver.Minor += 1
	return ver.String(), defaultPreReleaseId
}

func writeVersionToFile(version, preReleaseId, fileName string) error {
	f := NewFile("version")

	f.Comment("This file was generated by release_generate.go; DO NOT EDIT.")
	f.Line()

	f.Comment("Version is the version number in semver format X.Y.Z")
	f.Var().Id("Version").Op("=").Lit(version)

	f.Comment("PreReleaseID can be empty for releases, \"rc.X\" for release candidates and \"dev\" for snapshots")
	f.Var().Id("PreReleaseID").Op("=").Lit(preReleaseId)

	f.Comment("gitCommit is the short commit hash. It will be set by the linker.")
	f.Var().Id("gitCommit").Op("=").Lit("")

	f.Comment("buildDate is the time of the build with format yyyy-mm-ddThh:mm:ssZ. It will be set by the linker.")
	f.Var().Id("buildDate").Op("=").Lit("")

	buf := &bytes.Buffer{}
	if err := f.Render(buf); err != nil {
		return err
	}
	if err := ioutil.WriteFile(fileName, buf.Bytes(), 0644); err != nil {
		return err
	}
	return nil
}
