// Code generated by mockery v2.35.3. DO NOT EDIT.

package mocks

import (
	context "context"

	eks "github.com/aws/aws-sdk-go-v2/service/eks"
	mock "github.com/stretchr/testify/mock"
)

// VPCConfigUpdater is an autogenerated mock type for the VPCConfigUpdater type
type VPCConfigUpdater struct {
	mock.Mock
}

// UpdateClusterConfig provides a mock function with given fields: ctx, input
func (_m *VPCConfigUpdater) UpdateClusterConfig(ctx context.Context, input *eks.UpdateClusterConfigInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *eks.UpdateClusterConfigInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVPCConfigUpdater creates a new instance of VPCConfigUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVPCConfigUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *VPCConfigUpdater {
	mock := &VPCConfigUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
