package ami

// This file was generated by static_resolver_ami_generate.go; DO NOT EDIT.

// StaticImages is a map that holds the list of AMIs to be used by for static resolution
var StaticImages = map[string]map[string]map[int]map[string]string{
	"1.10": {
		"AmazonLinux2": {
			ImageClassGPU: {
				"ap-northeast-1": "ami-0afc9d14b2fe11ad9",
				"ap-northeast-2": "ami-0d75b9ab57bfc8c9a",
				"ap-southeast-1": "ami-0ecce0670cb66d17b",
				"ap-southeast-2": "ami-03b048bd9d3861ce9",
				"eu-central-1":   "ami-000622b1016d2a5bf",
				"eu-north-1":     "ami-cc149ab2",
				"eu-west-1":      "ami-0dafd3a1dc43781f7",
				"us-east-1":      "ami-0131c0ca222183def",
				"us-east-2":      "ami-0abfb3be33c196cbf",
				"us-west-2":      "ami-0ebf0561e61a2be02",
			},
			ImageClassGeneral: {
				"ap-northeast-1": "ami-06398bdd37d76571d",
				"ap-northeast-2": "ami-08a87e0a7c32fa649",
				"ap-southeast-1": "ami-0ac3510e44b5bf8ef",
				"ap-southeast-2": "ami-0d2c929ace88cfebe",
				"eu-central-1":   "ami-08eb700778f03ea94",
				"eu-north-1":     "ami-068b8a1efffd30eda",
				"eu-west-1":      "ami-0de10c614955da932",
				"us-east-1":      "ami-04358410d28eaab63",
				"us-east-2":      "ami-0b779e8ab57655b4b",
				"us-west-2":      "ami-09e1df3bad220af0b",
			},
		},
		"Ubuntu1804": {ImageClassGeneral: {
			"ap-northeast-1": "ami-0d1700e2b1ee4a7d1",
			"ap-northeast-2": "ami-0482114d05cc56007",
			"ap-southeast-1": "ami-02c9850ed9fb6e7dd",
			"ap-southeast-2": "ami-0e862d31afc398f91",
			"eu-central-1":   "ami-0734d5f3fa10dcafc",
			"eu-north-1":     "",
			"eu-west-1":      "ami-07036622490f7e97b",
			"us-east-1":      "ami-06fd8200ac0eb656d",
			"us-east-2":      "ami-0866798422f5d546b",
			"us-west-2":      "ami-6322011b",
		}},
	},
	"1.11": {
		"AmazonLinux2": {
			ImageClassGPU: {
				"ap-northeast-1": "ami-036b3969c5eb8d3cf",
				"ap-northeast-2": "ami-0b7f163f7194396f7",
				"ap-southeast-1": "ami-093f742654a955ee6",
				"ap-southeast-2": "ami-05e09575123ff498b",
				"eu-central-1":   "ami-0d6f0554fd4743a9d",
				"eu-north-1":     "ami-0b159b75",
				"eu-west-1":      "ami-097978e7acde1fd7c",
				"us-east-1":      "ami-0ff0241c02b279f50",
				"us-east-2":      "ami-006a12f54eaafc2b1",
				"us-west-2":      "ami-0c9e5e2d8caa9fb5e",
			},
			ImageClassGeneral: {
				"ap-northeast-1": "ami-0f0e8066383e7a2cb",
				"ap-northeast-2": "ami-0b7baa90de70f683f",
				"ap-southeast-1": "ami-019966ed970c18502",
				"ap-southeast-2": "ami-06ade0abbd8eca425",
				"eu-central-1":   "ami-010caa98bae9a09e2",
				"eu-north-1":     "ami-06ee67302ab7cf838",
				"eu-west-1":      "ami-01e08d22b9439c15a",
				"us-east-1":      "ami-0c24db5df6badc35a",
				"us-east-2":      "ami-0c2e8d28b1f854c68",
				"us-west-2":      "ami-0a2abab4107669c1b",
			},
		},
		"Ubuntu1804": {ImageClassGeneral: {
			"ap-northeast-1": "",
			"ap-northeast-2": "",
			"ap-southeast-1": "",
			"ap-southeast-2": "",
			"eu-central-1":   "",
			"eu-north-1":     "",
			"eu-west-1":      "",
			"us-east-1":      "",
			"us-east-2":      "",
			"us-west-2":      "",
		}},
	},
}
