// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocksv2

import (
	context "context"

	sts "github.com/aws/aws-sdk-go-v2/service/sts"
	mock "github.com/stretchr/testify/mock"
)

// STS is an autogenerated mock type for the STS type
type STS struct {
	mock.Mock
}

// GetCallerIdentity provides a mock function with given fields: ctx, params, optFns
func (_m *STS) GetCallerIdentity(ctx context.Context, params *sts.GetCallerIdentityInput, optFns ...func(*sts.Options)) (*sts.GetCallerIdentityOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetCallerIdentity")
	}

	var r0 *sts.GetCallerIdentityOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sts.GetCallerIdentityInput, ...func(*sts.Options)) (*sts.GetCallerIdentityOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sts.GetCallerIdentityInput, ...func(*sts.Options)) *sts.GetCallerIdentityOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sts.GetCallerIdentityOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sts.GetCallerIdentityInput, ...func(*sts.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSTS creates a new instance of STS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSTS(t interface {
	mock.TestingT
	Cleanup(func())
}) *STS {
	mock := &STS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
